import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from '../app/components/Header';
import { Footer } from '../app/components/Footer';
import { CartProvider } from './context/CartContext';  
import { CartSidebar } from "./components/Cart/CartSidebar";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function Layout({ children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <CartProvider>
          <div className="app min-h-screen flex flex-col">
            <Header />
            <main>{children}</main>
            <Footer />
            <CartSidebar />
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
